# Generated by Django 5.1.7 on 2025-03-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_week_friday_week_monday_week_saturday_week_sunday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
